apiVersion: v1
kind: PersistentVolume
metadata:
  name: open5gs-mongodb-pv
  labels:
    project: open5gs
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/kubedata/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cloud5gc1